[directory]
truncate_to_repo = false
truncation_length = 3
truncation_symbol = "…/"

[env_var.SHELL]
default = "unknown shell"

[git_status]
modified = '[++\($count\)](orange)'
staged = '[++\($count\)](green)'

[ruby]
disabled = true
